version: '3.3'

services:
  nginx:
    image: nginx:$TAG
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
    restart: always
    env_file: .env

  mariadb:
    image: mariadb:$TAG
    build: requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    image: wordpress:$TAG
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
    restart: always
    env_file: .env

networks:
  inception:

volumes:
  mariadb_data:
  wp_data:
